language: node_js
node_js:
- '7.6'
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: AwgVxBnqBBQkwXWOhgc4ZorimSZQi5NkCICPM3vBO6m+wuEH8Sab2X9dkkxBEECiR+qSEjU4ca1UuGO5cdYPdzJhMFGkH8RYBgI+anEf1bVITmtSNcfTy8wObMYKV8qE4Qb0hJXxBVBjAfCqtCAXw/Lj0pvWoRQ2DRSnEmsjOpS6ZBlPQRsimFDdwyHPXOWq8jUcJxc5dJLvht2w203yCccW0mbNPl/cEjytvhx17RrVZga25kxkw9YSGzF5z0UbXlpSmsrK2W5Y5tNKSiOzEXEYkG7ToD0Avj8pLgpd4kSOOmh5H+By41ywE70t0D+Dm9vfdZhDEK5dav9Zy8PAOHQXXYzWpfXfd1C4WPvZ/gRBqnvSMFeSkZyJ+qeGTAMaqTp74ZEx/s62SCBGlrwPba7bhvGqHaxs6Rc9DSnKF2AkYKiGTYa1yqLUXoow9BK7EnjTwUcSBgUBSm8wZNQ4dWuHMrgepRVoTzyoSbtYhmBM4K142Y0axXG3ton+Ye83/Ltu3u7BzBkhMKV9VK6FqzSuFBCCkmCyCrfgIuO+YJ6NYlJwWJJoG/lhdvjpGDyM5XsKmChLdVt+l9TxmaKF3Lwx7PgfH03NE3b0Rkx0uIpx36Jvb+dBbajDlrq89U05YQCQIn2QjpKRdw7FJt4Kv3wZ0Ur5h9DPATwu9RiabPo=
